import { useEffect } from "react";
import type { NextPage } from "next";
import Head from "next/head";

import { Box } from "@mui/material";
import { Navbar, SeasideTable } from "sdk/components";
import { SeasideAPI } from "sdk/services";

const Home: NextPage = () => {
    const service = new SeasideAPI();
    useEffect(() => {
        service.getApiHealth().then((res) => console.log(res));
    });
    return (
        <div>
            <Head>
                <title>SeasideFM Archives</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Box component={"main"}>
                <Navbar />
                <SeasideTable columns={[]} rows={[]} />
            </Box>
        </div>
    );
};

export default Home;
